config/routes.rb
Pollster::Application.routes.draw do
  
  root :to => 'polls#new'
  match '/polls/e/:edit_url', :to => 'polls#edit', :as => 'edit_obscured'
  match '/p/:name', :to => 'responses#new', :as => 'new_response'
  match '/answers', :to => 'answers#index', :as => 'answer_questions'
  
  resources :polls, :questions, :answers, :responses

end

app/models/answer.rb
class Answer < ActiveRecord::Base
  attr_accessible :question_id, :response_id, :text
  
  belongs_to :question
  belongs_to :response
end

app/models/poll.rb
class Poll < ActiveRecord::Base
  attr_accessible :edit_url, :name
    
  validates :name, :presence => true
  validates :edit_url, :uniqueness => true
  # validates :edit_url, :presence => true
  
  before_create :make_edit_url
  
  has_many :questions, :dependent => :destroy
  has_many :responses
  
  private
    def make_edit_url
      self.edit_url = SecureRandom.base64.gsub(/\W/,'')
    end
  
  # before_validation(:on => :create) do
    # self.edit_url  = SecureRandom.base64(10).gsub(/\W/,'')
    # self.edit_url = "haha"
  # end
end

app/models/question.rb
class Question < ActiveRecord::Base
  attr_accessible :poll_id, :text
  validates_presence_of :poll_id, :text
  
  belongs_to :poll
  has_many :answers, :dependent => :destroy
end

app/models/response.rb
class Response < ActiveRecord::Base
  attr_accessible :poll_id
  
  belongs_to :poll;
  has_many :answers, :dependent => :destroy
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  
  def create
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/polls_controller.rb
class PollsController < ApplicationController
  def index
    @polls = Poll.all
  end
  
  def show
    @poll = Poll.find(params[:id]) 
  end
  
  def edit
    @poll = Poll.find_by_edit_url(params[:edit_url])
  end
  
  def update
    poll = Poll.find(params[:id])
    poll.update_attributes(params[:poll])
    flash[:message] = "Updating...nbd"
    redirect_to edit_poll(poll.edit_url)
  end
  
  def new
    @poll = Poll.new
  end
  
  def create
    @poll = Poll.new(params[:poll])
    if @poll.save
      flash[:message] = "Look at you just creating polls like a boss."
      redirect_to poll_path(@poll.id)
    else
      flash[:error] = "Well that sucks. Something went wrong."
      render root_path
    end
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  def edit
    @question = Question.find(params[:id])
  end
  
  def update
    @question = Question.find(params[:id])
    @question.update_attributes(params[:question])
    flash[:message] = "Question updated!"
    redirect_to edit_obscured_path(@question.poll.edit_url)
  end
  
  def destroy
    @question = Question.find(params[:id])
    original_poll = @question.poll
    @question.destroy
    redirect_to edit_obscured_path(original_poll.edit_url)
  end
  
  def create
    @question = Question.new(params[:question])
    @question.save
    flash[:message] = "Nice question, chief."
    redirect_to edit_obscured_path(@question.poll.edit_url)
  end
  
end

app/controllers/responses_controller.rb
class ResponsesController < ApplicationController
  
  def new
    @poll = Poll.find_by_name(params[:name])
    @response = @poll.responses.new
  end
  
  def create
    @poll = Poll.find(params[:response][:poll_id])
    if session[:polls_taken] != @poll.id
      @response = @poll.responses.create
      create_answers
      flash[:message] = "You just created a response, you lucky duck.  Thanks for taking the survey."
      redirect_to new_response_path(@poll.name)
      session[:polls_taken] = @poll.id
    else
      flash[:notice] = "Sorry, you've already submitted this one, brah."
      redirect_to root_path
    end
  end
  
  private
    
    def create_answers
      #This feels strange and potentially slow.  There's got to be a better way.
      params.each { |k,v| @response.answers.create(:text => v, :question_id => k.to_i) if k =~ /^\d/ }
    end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/polls_helper.rb
module PollsHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_favicons.html.erb
<!-- Removing all favicons bc heroku complains they're not there. -->

app/views/layouts/_flashes.html.erb
<% if flash[:message]  %>
	<div class="alert alert-success"><%= flash[:message] %></div>
<% end %>
<% if flash[:notice]  %>
	<div class="alert alert-error"><%= flash[:notice] %></div>
<% end %>

app/views/layouts/_footer.html.erb
<footer>
  <!-- <p>&copy; Company 2012</p> -->
</footer>

app/views/layouts/_navbar.html.erb
<div class="navbar navbar-fixed-top">
  <div class="navbar-inner">
    <div class="container-fluid">
      <a class="btn btn-navbar" data-target=".nav-collapse" data-toggle="collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </a>
      <%= link_to "PJPollster", root_path, class: "brand" %>
    </div>
  </div>
</div>

app/views/layouts/_shim.html.erb
<!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
<!--[if lt IE 9]>
  <script src="http://html5shim.googlecode.com/svn/trunk/html5.js" type="text/javascript"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Pollster" %></title>
    <%= csrf_meta_tags %>

	<%= render :partial => 'layouts/shim' %>
    <%= stylesheet_link_tag "application", :media => "all" %>
	<%= render :partial => 'layouts/favicons' %>
</head>
  <body>
	<%= render :partial => 'layouts/navbar' %>
    <div class="container-fluid">
      <div class="row-fluid">
        <div class="span12">
		  <%= render :partial => 'layouts/flashes' %>

          <%= yield %>
        </div>
      </div><!--/row-->
	  <%= render :partial => 'layouts/footer' %>
    </div> <!-- /container -->
    <%= javascript_include_tag "application" %>
  </body>
</html>

app/views/layouts/old_application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Pollster</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/polls/_form.html.erb
<%= form_for poll do |f| %>
  <div class="form-inline">
    <%= f.text_field :name, :placeholder => 'Name your poll' %>  <%= f.submit :class => 'btn btn-primary btn-large' %>
  </div>
<% end %>

app/views/polls/_get_questions.html.erb
<% poll.questions.each do |question| %>
	<% if !question.text.nil? %>
		<%= render :partial => 'questions/display', :locals => {:question => question, :poll => poll }%>
	<% end %>
<% end %>

app/views/polls/edit.html.erb
<div class="hero-unit">
  <h1>Oh, hey.  You're back.</h1>
  <h3>You can <%= link_to "view this poll", poll_path(@poll.id)  %> or <%= link_to "share this poll", new_response_path(@poll.name) %></h3>

  <%= render :partial => 'polls/form', :locals => {:poll => @poll} %>

  <%= form_for @poll.questions.new do |f| %>
    <div class="form-inline">
	  <%= f.hidden_field :poll_id, :value => @poll.id %>
      <%= f.text_field :text, :placeholder => 'What do you want to ask?' %>  <%= f.submit :class => 'btn btn-primary btn-large' %>
    </div>
  <% end %>

  <% @poll.questions.each do |question| %>
	<% if !question.text.nil? %>
	  <%= render :partial => 'questions/display', :locals => {:question => question, :poll => @poll }%>
	<% end %>
  <% end %>
</div>

app/views/polls/index.html.erb
<div class="hero-unit">
  <ul>	
    <% @polls.each do |poll| %>
	  <li><%= link_to poll.name, poll_path(poll.id) %></li>
    <% end %>
  </ul>
</div>

app/views/polls/new.html.erb
<div class="hero-unit">
	<h1>You look like you want to make a poll</h1>
	<%= render :partial => 'polls/form', :locals => {:poll => @poll} %>
</div>

app/views/polls/show.html.erb
<div class="hero-unit">
  <h1><%= @poll.name %></h1>
  <h3>You can <%= link_to "edit this poll", edit_obscured_path(@poll.edit_url)  %> or <%= link_to "share this poll", new_response_path(@poll.name) %></h3>

  <% @poll.questions.each do |question| %>
	<% if !question.text.nil? %>
	  <%= render :partial => 'questions/display', :locals => {:question => question, :poll => @poll }%>
	<% end %>
  <% end %>
</div>

app/views/questions/_display.html.erb
<div class="questions">
	<%= question.text %>
	<% question.answers.each do |answer| %>
		<p>Response: <%= answer.text %></p>
	<% end %>
	<%= render :partial => 'questions/obscured_controls', :locals => {:question => question} %>
</div>

app/views/questions/_form.html.erb
Whatever needs _form has been moved to polls/edit

app/views/questions/_obscured_controls.html.erb
<% if request.path.split('/')[2] == "e" %>
	<%= link_to "Edit", edit_question_path(question.id) %>
	<%= link_to "Delete", question_path(question.id), :method => :delete %>
<% end %>

app/views/questions/edit.html.erb
<!-- Needs to be reconciled with _form -->
<div class="hero-unit">
	<h1>Sure, let's update that question of yours</h1>
	<%= form_for @question do |f| %>
	  <div class="form-inline">
	    <%= f.text_field :text, :placeholder => 'What do you want to ask?' %>  <%= f.submit :class => 'btn btn-primary' %>
	  </div>
	<% end %>
</div>

app/views/responses/new.html.erb
<div class="hero-unit">
	<h1><%= @poll.name %></h1>
	<%= form_for @poll.responses.new do |f| %>
		<%= f.hidden_field :poll_id, :value => @poll.id %>
		<p>
		  <% @poll.questions.each do |question| %>
			<%= label_tag question.text %>
			<%= text_field_tag question.id %>
		  <% end %>
		</p>
		<%= f.submit %>
	<% end %>
</div>

<%= debug session[:polls_taken] %>